id: P000594
initial_creation_type: ocr
source_metadata:
  id: bdr:W1PD159392
  title: དྲག་ཏུ་ལྡིང་བའི་ཡིག་འབྲུ་འདི་དག
  author: ''
  volumes:
    6793340f913e49e5bc5426228ad20b39:
      image_group_id: I2PD18312
      title: ''
      volume_number: 1
      total_pages: 188
